<script setup lang="ts">
import { fonts } from '~/data/fonts'
usePageSeo('Шрифтовые пары', 'Подберите шрифтовую пару онлайн: заголовок и основной текст, кириллица, живой предпросмотр и готовые сочетания.')
const heading = ref('cormorantgaramond')
const body = ref('manrope')
const title = ref('Красота в простых вещах.')
const paragraph = ref('У каждой истории есть свой голос. Шрифт помогает услышать его ещё до того, как мы прочитали первое предложение. Дай буквам немного воздуха — и они расскажут больше.')
const headingSize = ref(64)
const bodySize = ref(18)
const headingFont = computed(() => fonts.find(f => f.slug === heading.value)!)
const bodyFont = computed(() => fonts.find(f => f.slug === body.value)!)
const presets = [{ title: 'Редакционная', heading: 'cormorantgaramond', body: 'manrope' }, { title: 'Цифровая', heading: 'unbounded', body: 'golostext' }, { title: 'Спокойная', heading: 'lora', body: 'onest' }]
</script>
<template><div class="page-content content-pad"><div class="page-heading"><span class="eyebrow">Искусство сочетать</span><h1>Вместе — лучше.</h1><p>Один шрифт привлекает внимание. Другой помогает читать.</p></div><div class="pair-workspace"><aside class="pair-controls"><h2>Твоя пара</h2><label>Заголовок<select v-model="heading"><option v-for="font in fonts" :key="font.slug" :value="font.slug">{{ font.name }}</option></select></label><label class="range-label">Размер заголовка <output>{{ headingSize }} px</output><input v-model.number="headingSize" type="range" min="28" max="90" /></label><label>Основной текст<select v-model="body"><option v-for="font in fonts" :key="font.slug" :value="font.slug">{{ font.name }}</option></select></label><label class="range-label">Размер текста <output>{{ bodySize }} px</output><input v-model.number="bodySize" type="range" min="14" max="28" /></label><span class="eyebrow">Начать с готовой</span><div class="preset-list"><button v-for="preset in presets" :key="preset.title" :class="{ selected: heading === preset.heading && body === preset.body }" @click="heading = preset.heading; body = preset.body">{{ preset.title }} <span>↗</span></button></div></aside><section class="pair-preview"><div class="pair-preview-top"><span>Маленький журнал о большом</span><span>01 / 2026</span></div><label class="sr-only" for="pair-title">Текст заголовка</label><textarea id="pair-title" v-model="title" class="pair-title" maxlength="90" :style="{ fontFamily: `'${headingFont.name}'`, fontSize: `${headingSize}px`, fontWeight: headingFont.featuredWeight }" /><div class="pair-rule" /><label class="sr-only" for="pair-body">Основной текст</label><textarea id="pair-body" v-model="paragraph" class="pair-body" maxlength="900" :style="{ fontFamily: `'${bodyFont.name}'`, fontSize: `${bodySize}px` }" /><div class="pair-preview-bottom"><NuxtLink :to="`/fonts/${heading}`">{{ headingFont.name }} ↗</NuxtLink><span>+</span><NuxtLink :to="`/fonts/${body}`">{{ bodyFont.name }} ↗</NuxtLink></div></section></div><AdSlot /></div></template>
